# Generated by Django 4.1.1 on 2022-10-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variacao', 'verbose_name_plural': 'Variacoes'},
        ),
    ]
