# Generated by Django 4.1.1 on 2023-03-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtd_total',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
